"""Add_message_request_id_and_monthly_usages

Revision ID: 3b1a8c017118
Revises: b1475034bd00
Create Date: 2026-07-07 11:23:50.642440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1a8c017118'
down_revision: Union[str, None] = 'b1475034bd00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_estimate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_usages_month'), 'monthly_usages', ['month'], unique=True)
    op.add_column('messages', sa.Column('request_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_messages_request_id'), 'messages', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_request_id'), table_name='messages')
    op.drop_column('messages', 'request_id')
    op.drop_index(op.f('ix_monthly_usages_month'), table_name='monthly_usages')
    op.drop_table('monthly_usages')
    # ### end Alembic commands ###
