"""add_detected_language_to_document

Revision ID: 5b12740a8fd2
Revises: 3b1a8c017118
Create Date: 2026-07-07 12:54:49.166035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b12740a8fd2'
down_revision: Union[str, None] = '3b1a8c017118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('detected_language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'detected_language')
    # ### end Alembic commands ###
