"""Add_embedding_model_column

Revision ID: b1475034bd00
Revises: d750293b4d8e
Create Date: 2026-07-07 11:02:27.599624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1475034bd00'
down_revision: Union[str, None] = 'd750293b4d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_model')
    # ### end Alembic commands ###
